### PR TITLE
Add more line breaking commands

### PR DESCRIPTION
**Pull request by romildo**
Some additional basic LaTeX commands related to line breaking:

`lnbkspc`: `\\[extra-space]`

`lnbkspc_`: `\\*[extra-space]`

`eol`: empty comment (which will emit a new line)

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
Thanks, this looks good. One question only: can you justify defining `eol`? Any compelling examples of use?

**Comment by romildo** [comment]
> can you justify defining `eol`? Any compelling examples of use?

I use `eol` mainly to force new lines on the generated LaTeX output, making it easier to read and analyze what HaTeX is producing.

**Comment by Daniel-Diaz** [comment]
@romildo Have you tried the pretty printer? I think it should produce more readable LaTeX code.

**Comment by romildo** [comment]
>Have you tried the pretty printer?

Yes, I have. I use it, and also `eol` for more control on the HaTeX output.

**Pull request merged**
