### PR TITLE
Refactor/base math module

### PR DESCRIPTION
**Pull request by leftaroundabout**
In https://github.com/Daniel-Diaz/HaTeX/pull/120, it was discussed that the modules [`Packages.AMSMath`](http://hackage.haskell.org/package/HaTeX-3.19.0.0/docs/Text-LaTeX-Packages-AMSMath.html) and [`Base.Commands`](http://hackage.haskell.org/package/HaTeX-3.19.0.0/docs/Text-LaTeX-Base-Commands.html) aren't really consistent with where the respective commands are actually defined – in LaTeX itself or the [`amsmath` package](https://ctan.org/pkg/amsmath?lang=en), respectively.

This PR moves those maths commands that are already available in vanilla LaTeX into a new module [`Base.Math`]. Also adapted a commit by 0xCM from https://github.com/Daniel-Diaz/HaTeX/pull/123 that adds some symbols.

What should be discussed: currently, the export list is kept expanded in the AMSMath module, i.e. the docs to this module still list things that actually don't come from `amsmath`. I think this is actually not bad, because it allows the AMSMath module to be read like a “Prelude for mathematical HaTeX”.

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
Very nice job! Thanks!

**Comment by Daniel-Diaz** [comment]
And yes, I agree with re-exporting `Base.Math` from `Packages.AMSMath`.

**Comment by leftaroundabout** [comment]
Already two months gone – I forgot, was there anything still left to be done with this issue?

If not, could we make a new release here? Not sure if it should be 3.19.1.0 or 3.20.0.0 or even 4.0.0.0. But I could use to have the new symbols [in dependent projects](https://github.com/leftaroundabout/Symbolic-math-HaTeX/issues/1).

**Comment by Daniel-Diaz** [comment]
I have just uploaded HaTeX-3.20.0.0. I don't think the changes are so drastic that they require the version to go to 4.

**Pull request merged**
