### PR TITLE
New symbols for AMSSymb; new coproduct, bigcap, bigcup for AMSMath; n…

### PR DESCRIPTION
**Pull request by 0xCM**
…ew quaternions number set for AMSFonts

### CODE REVIEW

**Comment by leftaroundabout** [comment]
Nice; I assume you have read https://github.com/Daniel-Diaz/HaTeX/pull/120? There we discussed the problematic of the maths commands being currently, inconsistently, all in `AMSMath`. I've started factoring this out into a `Text.LaTeX.Base.Math` module (which turns out to be less straightforward than expected, because the [AMS-LaTeX documention](http://ctan.math.illinois.edu/macros/latex/required/amsmath/amsldoc.pdf) hardly bothers listing what exactly each package does).

Are the symbols you're adding to the `AMSSymb` module here all really from the `amssymb` package?

**Comment by leftaroundabout** [comment]
I adapted your commit to the intended new module structure which better mirrors the way the commands are actually defined in LaTeX. Please check https://github.com/Daniel-Diaz/HaTeX/pull/124/commits/46db4e2b464e690fc2fbcf79b6410e1979cfe521.

**Comment by leftaroundabout** [comment]
https://github.com/Daniel-Diaz/HaTeX/pull/124

**Comment by 0xCM** [comment]
> Nice; I assume you have read #120? 
Sorry it's taken me so long to respond; I didn't notice I had any pending messages. And no, I wasn't aware of #120; I just needed a couple of arrows and added  a batch of them. And yeah, I did notice there was confusion regarding which symbols required the additional AMS package; as you note, the documentation on the packages wasn't really helpful. Thanks for getting it sorted out.

**Pull request closed without merging**
