### PR TITLE
Changes for wl-pprint-extras-3.5

### PR DESCRIPTION
**Pull request by ddssff**

### CODE REVIEW

**Comment by leftaroundabout** [comment]
That extra argument has only been introduced in `wl-pprint-extras-3.6` (which is not even on Hackage yet). Version 3.5 still has the old API.

**Comment by Daniel-Diaz** [comment]
Wow, yeah. Let's wait until we can test this against a released version. Note that the automatic checks are failing.

Thanks @ddssff !

**Comment by ddssff** [comment]
Oh, I see.

**Comment by Daniel-Diaz** [comment]
No need to close, we can leave it open until we can get the tests to pass. If you want.

**Comment by ddssff** [comment]
No, it would be a bit confusing when you came back to it.

**Pull request closed without merging**
