### PR TITLE
Support for parsec 3.1.9 fpco/stackage#485

### PR DESCRIPTION
**Pull request by snoyberg**

### CODE REVIEW

**Comment by Daniel-Diaz** [comment]
Thanks!

**Comment by snoyberg** [comment]
Would it be possible to release this change to Hackage so that I can unblock parsec-3.1.9?

**Comment by Daniel-Diaz** [comment]
HaTeX-3.16.1.0 released, including this change.

**Comment by snoyberg** [comment]
Thanks!

**Pull request merged**
