### PR TITLE
Add mapLaTeXT, a helper function for building trans monad instances

### PR DESCRIPTION
**Pull request by ddssff**
This function is analogous to mapErrorT, mapExceptT, mapStateT, etc.

### CODE REVIEW

**Comment by ddssff** [comment]
A release with this addition would be very helpful because it can't be implemented without access to un-exported symbols.

**Comment by Daniel-Diaz** [comment]
OK. I will prepare a release.

Thanks!

**Comment by ddssff** [comment]
Could we have a hackage upload with this change?  Thanks!

**Comment by Daniel-Diaz** [comment]
HaTeX-3.17.1.0 released. It includes this change. See [Hackage](http://hackage.haskell.org/package/HaTeX-3.17.1.0).

**Pull request merged**
